UIwo
hsakurai-cq/BookApp pull request #1
Opened 2017-07-28 09:53 UTC by hsakurai-cq

2017-07-31 01:20 UTC, ykawakami-cq reviewed
レビューしました！

2017-07-31 01:20 UTC, ykawakami-cq commented on app/build.gradle
> +    compile 'com.android.support:support-v4:26.+'
dependenciesのバージョンは基本的に固定で指定することが推奨されています。
Android Studioでも警告が出ていて、理由についてもマウスオーバーで表示されます。

2017-07-31 01:20 UTC, ykawakami-cq commented on app/src/main/java/com/hiromisakurai/bookapp/CustomBookListAdapter.java
> +        if (convertView !=null) {
スペース空けたほうがいいかな。

2017-07-31 01:20 UTC, ykawakami-cq commented on app/src/main/java/com/hiromisakurai/bookapp/EditBookFragment.java
> +    }
コンストラクタが特に必要ないのであれば削除しても問題ないです。

2017-07-31 01:20 UTC, ykawakami-cq commented on app/src/main/java/com/hiromisakurai/bookapp/LoginActivity.java
> +                }else if (TextUtils.isEmpty(loginPassword)) {
} else if ...

2017-07-31 01:20 UTC, ykawakami-cq commented on app/src/main/java/com/hiromisakurai/bookapp/ValidationUtil.java
> +        if (title.isEmpty()) {
isEmptyは空文字列かどうかを判定するので、もし`null`が入っていた場合にNullPointerExceptionが発生します。
`TextUtils.isEmpty`を利用すると`null`と`0 length`を両方判定できます。

2017-07-31 01:20 UTC, ykawakami-cq commented on app/src/main/java/com/hiromisakurai/bookapp/BookListFragment.java
> +        ArrayList<Book> listItems = new ArrayList<>();
ArrayList固有のメソッドを使用しない場合は、拡張性なども考えて（研修では機能追加などしないですが）
`List<Book> listItems = new ArrayList<>();`で書くほうがいいようです。
http://www.sejuku.net/blog/14886

2017-07-31 01:32 UTC, ykawakami-cq commented on app/src/main/AndroidManifest.xml
> +        android:label=""
`<string name="app_name">Book App</string>`が定義してあるのでそのままでいいような

2017-07-31 03:21 UTC, ykawakami-cq reviewed
再度コメントしましたー。

2017-07-31 03:21 UTC, ykawakami-cq commented on app/src/main/java/com/hiromisakurai/bookapp/EditBookFragment.java
> +    EditText txtDate;
こちらも`private`

2017-07-31 03:21 UTC, ykawakami-cq commented on app/src/main/java/com/hiromisakurai/bookapp/AddBookActivity.java
> +    EditText txtDate;
外部から呼び出す必要がなければ`private`にした方がいいです。

2017-07-31 06:26 UTC, hyoshimi-cq commented on app/src/main/java/com/hiromisakurai/bookapp/BookListFragment.java
> +    private static String BUNDLE_DATE = "purchaseDate";
定数にしたいのであれば `private static final String BUNDLE_DATE = "purchaseDate";` ですー

2017-07-31 06:26 UTC, hyoshimi-cq commented on app/src/main/java/com/hiromisakurai/bookapp/EditBookFragment.java
> +        Bitmap img = bundle.getParcelable(BUNDLE_IMAGE);
Bundleのkeyは同じ定数を使用した方が良いですね。
つまり `BookListFragment` 値を入れる際に使用するkeyと `EditBookFragment` で取り出すkeyを同じにするってことです。

2017-07-31 06:26 UTC, hyoshimi-cq commented on app/src/main/java/com/hiromisakurai/bookapp/DateDialog.java
> +    private EditText txtDate;
`EditText` (View全般)をメンバ変数に持っておいてそれを操作するのはあまりよくないですね。

今回の場合は選択した日付（int year, int month, int day）を返すようなinterfaceを用意しておけば解決するかなと思います。

2017-07-31 06:26 UTC, hyoshimi-cq commented on app/src/main/java/com/hiromisakurai/bookapp/DateDialog.java
> +        txtDate = (EditText)view;
ここでキャストするのはあまりよくないです。
このコンストラクタはViewであればEditText以外でも許容するのでEditText以外が来た場合には落ちます。

2017-07-31 06:26 UTC, hyoshimi-cq commented on app/src/main/java/com/hiromisakurai/bookapp/MainActivity.java
> +            startActivity(intent);
`return true` ?

2017-07-31 06:26 UTC, hyoshimi-cq commented on app/src/main/java/com/hiromisakurai/bookapp/ValidationUtil.java
> +        return valid;
これって全部空だったら全部のダイアログが出ますよね？
使いやすさを考えなくても良いかとは思うんですが、ダイアログ出過ぎは微妙です。。。

2017-07-31 09:56 UTC, hyoshimi-cq commented on app/src/main/java/com/hiromisakurai/bookapp/DateDialog.java
> +        textView.setText(dateStr);
先ほど言ったのは以下のようにして `onDateDialogClickListener` を各ActivityなりFragmentなりで受け取れるようにしておいてTextViewにsetTextするのはそれぞれでやらせるっていうことです。iOSのdelegateだと思ってもらえれば。

```java
public class DateDialog extends ... {

  public interface OnDateDialogClickListener {
    void onDateDialogClickListener(int year, int month, int day);
  }

  private OnDateDialogClickListener listener;
  public void setListener(OnDateDialogClickListener listener) {
    this.listener = listener;
  }

  public void onDateSet(DatePicker view, int year, int month, int day) {
    if (listener != null) {
      onDateDialogClickListener(year, month, day);
    }
  }
}
```

2017-07-31 09:56 UTC, hyoshimi-cq commented on app/src/main/java/com/hiromisakurai/bookapp/ValidationUtil.java
> +        ArrayList<String> errorArray = new ArrayList<String>();
`private List<String> errorArray = new ArrayList<>()` 
基本的には上記のように書いた方がいいです
参考： http://qiita.com/Mura-Mi/items/e52c28ab7cb5db140d53

2017-07-31 12:11 UTC, hyoshimi-cq commented on app/src/main/java/com/hiromisakurai/bookapp/MainActivity.java
> +            startActivity(intent);
他の `onOptionsItemSelected` だとtrue返してるけどここも返さないとじゃないですか？？

2017-07-31 12:12 UTC, hyoshimi-cq commented
@hsakurai-cq 
1つコメントしました！
他は大丈夫そうです！

2017-08-01 02:54 UTC, ghost requested changes

2017-08-01 02:54 UTC, yiino-cq commented on app/build.gradle
> +    compile 'com.android.support:appcompat-v7:25.0.0'
なぜバージョンを下げた? 26.0.0使えると思います

2017-08-01 02:54 UTC, yiino-cq commented on app/src/main/java/com/hiromisakurai/bookapp/AccountActivity.java
> +                EditText emailET = (EditText) findViewById(R.id.AccountEmailEditText);
androidでは省略形の命名は(あまり)しないので頭の片隅に入れておくといいかんじ

2017-08-01 02:54 UTC, yiino-cq commented on app/src/main/java/com/hiromisakurai/bookapp/AddBookActivity.java
> +    public void onStart() {
`@Override`

2017-08-01 02:54 UTC, yiino-cq commented on app/src/main/java/com/hiromisakurai/bookapp/Book.java
> +    private Bitmap mBookImage = null;
https://github.com/yyamakawa-cq/kenshu_android/pull/1#issuecomment-317983671

2017-08-01 02:54 UTC, yiino-cq commented on app/src/main/java/com/hiromisakurai/bookapp/EditBookFragment.java
> +        Bitmap img = bundle.getParcelable(BookListFragment.BUNDLE_IMAGE);
これはちょっと微妙です。 `BookListFragment`と `EditBookFragment`の関係を考えてみてほしいのですが
`EditBookFragment`は自分が使う情報を知っていて定義できるはずなのでそれを `BookListFragment`に見に行く必要はないです。 見に行ってしまうと `EditBookFragment`から `BookListFragment`への依存が出来てしまいます。

例えば将来 `EditBookFragment`を `BookListFragment`以外から開けるようにしたり編集できる内容を変更したりと言う場合に、なぜか `BookListFragment`の定義を変更しなくてはいけなくなってしまいます


CC: @hyoshimi-cq @ykawakami-cq

2017-08-01 02:54 UTC, yiino-cq commented on app/src/main/java/com/hiromisakurai/bookapp/ValidationUtil.java
> +            ErrorDialogUtil.showDialog(errorMessages, context);
https://github.com/kfukazawa-cq/bookManager-android/pull/7#discussion_r121364808
https://github.com/kfukazawa-cq/bookManager-android/pull/7#discussion_r121366921

2017-08-01 02:54 UTC, yiino-cq commented on app/src/main/java/com/hiromisakurai/bookapp/ValidationUtil.java
> +    static public boolean validateLogin(String email, String password, Context context) {
修飾子の順番は統一してください
大抵 public static finalの順が使われます
参考:https://google.github.io/styleguide/javaguide.html#s4.8.7-modifiers

2017-08-01 02:54 UTC, yiino-cq commented on app/src/main/res/layout/activity_account.xml
> +    <android.support.v7.widget.Toolbar xmlns:android="http://schemas.android.com/apk/res/android"
xmlnsはトップにだけ宣言すれば他では不要です

2017-08-01 02:54 UTC, yiino-cq commented on app/src/main/res/layout/activity_account.xml
> +            android:id="@+id/AccountEmailEditText"
たまに大文字から始まってるIDがあり統一感ないので揃えましょう

2017-08-01 02:55 UTC, yiino-cq commented
@hsakurai-cq :eyes:ed 見ました

2017-08-01 07:03 UTC, hsakurai-cq commented on app/src/main/java/com/hiromisakurai/bookapp/ValidationUtil.java
> +            ErrorDialogUtil.showDialog(errorMessages, context);
```ValidationUtil.validateLogin ```メソッドの返り値は必ず true/false ではないとダメですか？
文字列を返すのはダメでしょうか？
このメソッドでどの```EditText```が空なのかをチェック(&ダイアログのメッセージに反映)しようと思ったのですが。。。
それは違うクラスでやる方がいいでしょうか？
今は、単純に１種類のアラートメッセージを出しています。

2017-08-01 07:05 UTC, hsakurai-cq commented on app/src/main/java/com/hiromisakurai/bookapp/ValidationUtil.java
> +    static public boolean validateLogin(String email, String password, Context context) {
ありがとうございます。

2017-08-01 07:07 UTC, hsakurai-cq commented on app/build.gradle
> +    compile 'com.android.support:appcompat-v7:25.0.0'
26.0.0だとなぜかエラーが出たので一旦エラーが出ない25.0.0でやっていました。
もう一回やってみます。

2017-08-01 07:27 UTC, yiino-cq commented on app/src/main/java/com/hiromisakurai/bookapp/ValidationUtil.java
> +            ErrorDialogUtil.showDialog(errorMessages, context);
複数の値を変えたいのであればそういう値を持ったクラスを作れば良いです。

```java
class ValidationErrors {
  final boolean emailEmpty;
  final boolean passwordEmpty;
  public ValidationErrors(boolean emailEmpty, boolean passwordEmpty) {
    this.emailEmpty = emailEmpty;
    this.passwordEmpty = passwordEmpty;
  }
}

```

もしくはメッセージだけで良いのであれば `errorArray`を返してしまえば良いです
```java
List<String> errors = validateLogin(...);
boolean valid = errors.isEmpty();
```

2017-08-01 08:55 UTC, hsakurai-cq commented on app/src/main/java/com/hiromisakurai/bookapp/ValidationUtil.java
> +            ErrorDialogUtil.showDialog(errorMessages, context);
文字列を返して、それが空かどうかをチェックするように修正しました。

2017-08-01 08:56 UTC, hsakurai-cq commented on app/src/main/java/com/hiromisakurai/bookapp/EditBookFragment.java
> +        Bitmap img = bundle.getParcelable(BookListFragment.BUNDLE_IMAGE);
Bundle Key は Constants class を参照するように変更しました。

2017-08-01 09:01 UTC, ghost reviewed
👍  :yosasou:

2017-08-01 09:10 UTC, merged